### ISSUE TITLE
Diff interpreter

### ISSUE THREAD

**Issue by dmalikov** [biegunka/biegunka#54]
As a `biegunka-core` user I want to be able to get diff for all files maintained by `biegunka`.

It works well for files installed with `link` command. It will be nice to have some similar mechanism for files installed with `copy`.

**Comment by supki** [comment]
I've done some work on this in `5df8989`. All changes to the content of the files managed by biegunka are logged to standard output during `biegunka run`. The only remaining task is to decouple logging from the actual `I/O`.

**Comment by supki** [comment]
There may actually be a problem. We cannot show the correct diff unless we update the sources, but the update itself can change the state of the system (through symlinks). What do we do about this?

**Comment by supki** [comment]
6b8293e63501993a40cc6cbce2f2ccfb4b8fb319 is an attempt to implement this. All actions are split into two parts: the first one prepares the update and can calculate the diff, the second one actually performs the update. The diff is (possibly) inaccurate through, due to the aforementioned problem.
